### ISSUE TITLE
`ExitCode` error on upgrade

### ISSUE THREAD

**Issue by 0atman** [alda-lang/alda-core#68]
When I upgraded from 1.0.1 to 1.1.0, with `alda update`, I got this error:
```java
Exception in thread "main" java.lang.NoClassDefFoundError: alda/error/ExitCode
```

However, when I re-run the update, my alda has been updated successfully.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-client-java/issues/38.
